#!/bin/bash
if [ "$1" = "list" ]; then
echo '"Virtual core pointer"   id=0   [XPointer]
"Virtual core keyboard"   id=1   [XKeyboard]
"CNF7129"   id=2   [XExtensionKeyboard]
"AT Translated Set 2 keyboard"   id=3   [XExtensionKeyboard]
"Asus EeePC extra buttons"   id=4   [XExtensionKeyboard]
"Sleep Button"   id=5   [XExtensionKeyboard]
"Power Button"   id=6   [XExtensionKeyboard]
"Power Button"   id=7   [XExtensionKeyboard]
"Video Bus"   id=8   [XExtensionKeyboard]
"ETPS/2 Elantech Touchpad"   id=9   [XExtensionPointer]'
elif [ "$1" = "list-props" ]; then
echo 'Device 'ETPS/2 Elantech Touchpad':
   Device Enabled (110):   1
   Synaptics Edges (248):   53, 1099, 48, 720
   Synaptics Finger (249):   25, 30, 256
   Synaptics Tap Time (250):   180
   Synaptics Tap Move (251):   59
   Synaptics Tap Durations (252):   180, 180, 100
   Synaptics Tap FastTap (253):   0
   Synaptics Middle Button Timeout (254):   75
   Synaptics Two-Finger Pressure (255):   257
   Synaptics Two-Finger Width (256):   7
   Synaptics Scrolling Distance (257):   27, 27
   Synaptics Edge Scrolling (258):   0, 0, 0
   Synaptics Two-Finger Scrolling (259):   1, 0
   Synaptics Move Speed (260):   0.400000, 0.700000, 0.036711, 40.000000
   Synaptics Edge Motion Pressure (261):   30, 160
   Synaptics Edge Motion Speed (262):   1, 108
   Synaptics Edge Motion Always (263):   0
   Synaptics Button Scrolling (264):   1, 1
   Synaptics Button Scrolling Repeat (265):   1, 1
   Synaptics Button Scrolling Time (266):   100
   Synaptics Off (267):   0
   Synaptics Guestmouse Off (268):   0
   Synaptics Locked Drags (269):   0
   Synaptics Locked Drags Timeout (270):   5000
   Synaptics Tap Action (271):   0, 0, 0, 0, 1, 3, 2
   Synaptics Click Action (272):   1, 1, 1
   Synaptics Circular Scrolling (273):   0
   Synaptics Circular Scrolling Distance (274):   0.100000
   Synaptics Circular Scrolling Trigger (275):   0
   Synaptics Circular Pad (276):   0
   Synaptics Palm Detection (277):   0
   Synaptics Palm Dimensions (278):   10, 200
   Synaptics Coasting Speed (279):   0.000000
   Synaptics Pressure Motion (280):   30, 160
   Synaptics Pressure Motion Factor (281):   1.000000, 1.000000
   Synaptics Grab Event Device (282):   1
   Synaptics Gestures (283):   1
   Synaptics Capabilities (284):   1, 1, 1, 1, 1
   Synaptics Pad Resolution (285):   1, 1
   Synaptics Area (286):   0, 0, 0, 0'
fi
