#!/bin/bash
if [ "$1" = "list" ]; then
echo '"Virtual core pointer"   id=0   [XPointer]
"Virtual core keyboard"   id=1   [XKeyboard]
"AT Translated Set 2 keyboard"   id=3   [XExtensionKeyboard]
"Asus EeePC extra buttons"   id=4   [XExtensionKeyboard]
"Video Bus"   id=5   [XExtensionKeyboard]
"Sleep Button"   id=6   [XExtensionKeyboard]
"Power Button"   id=7   [XExtensionKeyboard]
"Power Button"   id=8   [XExtensionKeyboard]
"ETPS/2 Elantech Touchpad"   id=9   [XExtensionPointer]
"USB Mouse"   id=10   [XExtensionPointer]'
elif [ "$1" = "list-props" ]; then
echo 'Device 'ETPS/2 Elantech Touchpad':
   Device Enabled (110):   1
   Synaptics Edges (246):   53, 1099, 48, 720
   Synaptics Finger (247):   25, 30, 256
   Synaptics Tap Time (248):   180
   Synaptics Tap Move (249):   59
   Synaptics Tap Durations (250):   180, 180, 100
   Synaptics Tap FastTap (251):   0
   Synaptics Middle Button Timeout (252):   75
   Synaptics Two-Finger Pressure (253):   257
   Synaptics Two-Finger Width (254):   7
   Synaptics Scrolling Distance (255):   27, 27
   Synaptics Edge Scrolling (256):   0, 0, 0
   Synaptics Two-Finger Scrolling (257):   1, 1
   Synaptics Move Speed (258):   0.400000, 0.700000, 0.036711, 40.000000
   Synaptics Edge Motion Pressure (259):   30, 160
   Synaptics Edge Motion Speed (260):   1, 108
   Synaptics Edge Motion Always (261):   0
   Synaptics Button Scrolling (262):   1, 1
   Synaptics Button Scrolling Repeat (263):   1, 1
   Synaptics Button Scrolling Time (264):   100
   Synaptics Off (265):   0
   Synaptics Guestmouse Off (266):   0
   Synaptics Locked Drags (267):   0
   Synaptics Locked Drags Timeout (268):   5000
   Synaptics Tap Action (269):   0, 0, 0, 0, 1, 3, 2
   Synaptics Click Action (270):   1, 1, 1
   Synaptics Circular Scrolling (271):   0
   Synaptics Circular Scrolling Distance (272):   0.100000
   Synaptics Circular Scrolling Trigger (273):   0
   Synaptics Circular Pad (274):   0
   Synaptics Palm Detection (275):   0
   Synaptics Palm Dimensions (276):   10, 200
   Synaptics Coasting Speed (277):   0.000000
   Synaptics Pressure Motion (278):   30, 160
   Synaptics Pressure Motion Factor (279):   1.000000, 1.000000
   Synaptics Grab Event Device (280):   1
   Synaptics Gestures (281):   1
   Synaptics Capabilities (282):   1, 1, 1, 1, 1
   Synaptics Pad Resolution (283):   1, 1
   Synaptics Area (284):   0, 0, 0, 0'
fi
