#!/bin/bash
if [ "$1" = "list" ]; then
echo "⎡ Virtual core pointer                        id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                  id=4    [slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                    id=13    [slave  pointer  (2)]
⎜   ↳ Macintosh mouse button emulation            id=14    [slave  pointer  (2)]
⎣ Virtual core keyboard                       id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard                 id=5    [slave  keyboard (3)]
    ↳ Power Button                                id=6    [slave  keyboard (3)]
    ↳ Video Bus                                   id=7    [slave  keyboard (3)]
    ↳ Power Button                                id=8    [slave  keyboard (3)]
    ↳ Sleep Button                                id=9    [slave  keyboard (3)]
    ↳ CNF7129                                     id=10    [slave  keyboard (3)]
    ↳ Asus EeePC extra buttons                    id=11    [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard                id=12    [slave  keyboard (3)]"
elif [ "$1" = "list-props" ]; then
echo "Device 'ETPS/2 Elantech Touchpad':
    Device Enabled (133):    1
    Device Accel Profile (250):    0
    Device Accel Constant Deceleration (251):    1.000000
    Device Accel Adaptive Deceleration (253):    1.000000
    Device Accel Velocity Scaling (254):    10.000000
    Synaptics Edges (255):    53, 1099, 48, 720
    Synaptics Finger (256):    25, 30, 256
    Synaptics Tap Time (257):    180
    Synaptics Tap Move (258):    59
    Synaptics Tap Durations (259):    180, 180, 100
    Synaptics Tap FastTap (260):    0
    Synaptics Middle Button Timeout (261):    75
    Synaptics Two-Finger Pressure (262):    257
    Synaptics Two-Finger Width (263):    7
    Synaptics Scrolling Distance (264):    27, 27
    Synaptics Edge Scrolling (265):    0, 0, 0
    Synaptics Two-Finger Scrolling (266):    1, 0
    Synaptics Move Speed (267):    0.400000, 0.700000, 0.036711, 40.000000
    Synaptics Edge Motion Pressure (268):    30, 160
    Synaptics Edge Motion Speed (269):    1, 108
    Synaptics Edge Motion Always (270):    0
    Synaptics Button Scrolling (271):    1, 1
    Synaptics Button Scrolling Repeat (272):    1, 1
    Synaptics Button Scrolling Time (273):    100
    Synaptics Off (274):    0
    Synaptics Guestmouse Off (275):    0
    Synaptics Locked Drags (276):    0
    Synaptics Locked Drags Timeout (277):    5000
    Synaptics Tap Action (278):    0, 0, 0, 0, 1, 3, 2
    Synaptics Click Action (279):    1, 1, 1
    Synaptics Circular Scrolling (280):    0
    Synaptics Circular Scrolling Distance (281):    0.100000
    Synaptics Circular Scrolling Trigger (282):    0
    Synaptics Circular Pad (283):    0
    Synaptics Palm Detection (284):    0
    Synaptics Palm Dimensions (285):    10, 200
    Synaptics Coasting Speed (286):    0.000000
    Synaptics Pressure Motion (287):    30, 160
    Synaptics Pressure Motion Factor (288):    1.000000, 1.000000
    Synaptics Grab Event Device (289):    1
    Synaptics Gestures (290):    1
    Synaptics Capabilities (291):    1, 0, 1, 1, 1
    Synaptics Pad Resolution (292):    1, 1
    Synaptics Area (293):    0, 0, 0, 0"
fi
