#!/bin/bash
#
# Jupiter restore settings on resume
#
#

JUPITER_PATH="/usr/lib/jupiter/scripts"
JUPITER_VAR="/var/jupiter"

if [ ! -d "$JUPITER_VAR" ]; then
  mkdir -p $JUPITER_VAR >/dev/null 2>&1 || true
  chown -R root:jupiter $JUPITER_VAR >/dev/null 2>&1 || true
  chmod 775 $JUPITER_VAR >/dev/null 2>&1 || true
  chmod ug+s $JUPITER_VAR >/dev/null 2>&1 || true
  setfacl -Rm g:jupiter:rwX,d:g:jupiter:rwX . >/dev/null 2>&1 || true
fi

case "$1" in
  hibernate|suspend|sleep)
    ;;
  thaw|resume)
    USER=$(who | sed -n '/ (:0[\.0]*)$\| :0 /{s/ .*//p;q}')
    if [ -e "$JUPITER_VAR/bt_saved" ]; then
      sudo $JUPITER_PATH/bluetooth restore 2>/dev/null &
    fi

    if [ -e "$JUPITER_VAR/wifi_saved" ]; then
      sudo $JUPITER_PATH/wifi restore silent 2>/dev/null
    fi

    if [ -e "$JUPITER_VAR/touchpad_saved" ]; then
      su $USER -l -c "DISPLAY=:0.0 $JUPITER_PATH/touchpad restore silent" 2>/dev/null &
    fi

    ;;
  *) exit $NA
    ;;
esac
